### ISSUE TITLE
General Issues / To Do List

### ISSUE THREAD

**Issue by jimfrize** [Awesome-Game-Team/Awesome-Game#15]
- CPU usage is too much
- Can’t toggle mute without entering fullscreen
- Character needs a tighter collision boundary
- Jetpack does not work in fullscreen
- Need to reduce the high frequencies in the music by around 3 to 6db
- Melodies and rhythms need to be more varied
- I want to be able to use animated objects from Tiled map editor
- Could have the jetpack work with the jump key “flappy bird style” - it would reduce the number of buttons to three, which would be good for touch screen mode

**Comment by jimfrize** [comment]
<img width="521" alt="screen shot 2016-05-16 at 08 16 23" src="https://cloud.githubusercontent.com/assets/12966015/15283619/d8a565a8-1b43-11e6-9b8b-a5a1a61a4730.png">

42.2% CPU usage!!! & I'm running a 2.7 GHz Intel Core i7 with a NVIDIA GeForce GT 650M 1024 MB GFX card

**Comment by metalx1000** [comment]
- I'm not sure what can be done about the CPU usage.  But, I don't trust numbers, I look at how things run.  I can't test it to well on my phone right now, since we don't have onscreen controls yet, but I test things on my tablet and phone.  My Phone is a 2014 Moto G.  Brand new 2 years ago this was a $179 phone.  The way I look at it, if it will run well on that, then it's good to go.  I'm not against improving it, but if it's running good, it's not high priority for me.  I've created more complex games that have run fine on my phone.
- No sound on startup at all, or just delayed?  If Delayed it's due to the music compression.  We talked about this and chose to remove the WAV files due to lower audio quality.  I went along with this because you wrote the music and I don't want you to be unhappy with the way it sounds. We still need to make a loading screen for things like this to load.
- We can enable fullscreen another way, but as far as I see the game, it's meant to be played in fullscreen, so once you interact with it (touching the mute button) it will go fullscreen.  We can also have the game remember a users settings.  That way, if they mute the music, it will be muted the next time they start the game.  Would that help this issue?
- To tighten the bounds we need to trim up the player.png and remove the spaces.  At lest this is the easiest way I know of.
- The Jetpack works for me in full screen.  We'll have to look into this.
- My first thought is that the music is in mp3/ogg format which would cause the decompression delay, but I would think that it should already be decompressed.  I haven't noticed a delay in the loop, but I wasn't looking for it either.  We'll have to look into this.
- We can adjust volume levels in the scripting, but I think you are talking about tweaking the music file itself here.  Is that correct?
- Animated object is the Tiled Editor?  Not sure what you mean by this.

-The jet pack does run out after some time of usage, there is just no power bar displayed on screen yet.  There is a variable that controls this for the player - player.jet - which you can check in the console currently.

-We can discuss this more.  I didn't link it to the jump button because I thought some people might want to save the Jetpack Fuel until they needed it, and if we link it to the jump button every time they jump it would use up a little bit of power.

Thanks for posting all this.  Lots of good stuff here to look into and think about.

**Comment by jimfrize** [comment]
@metalx1000 Just made a few changes, been working my way through this list. I've been removing things from the list once I've done them. Just sent you the pull request :)

**Comment by jonpatterns** [comment]
It may be useful to have a todo text file in the repository/ or maybe a wiki page. What do people think about a title page - here the different options could be set and or in game menu.

**Comment by jimfrize** [comment]
@metalx1000 When I first load the page I don't get music or SFX, no matter how long I wait. If I refresh the page the sound comes back immediately.

I think using a different key for fullscreen might be good solution, maybe "F". But I'm cool with it either way.

I adjusted the levels of the SFX and music by editing the audio files, so that they are all balanced together. The music still needs adjustment, but I'll probably rewrite the track, so I can adjust the levels of the music then.

In Tiled you can create animated objects using a tile set, they look awesome! But when I saved out the .JSON file to test it in the game it just displayed all the frames in the image and I you don't get any animation. But I will definitely look into it, people who might not be comfortable submitting code, GFX and SFX to the project might want to build levels for the game, and animated objects would be a pretty cool addition to that process :)

The only reason I was suggesting we combine the jump and fly button was to save on screen space and keep the control interface minimal - just a thought really.

Wow! you get a lot of gas in those jump packs ;) I've been flying around all over the place and I didn't even realise they run out!

**Comment by jimfrize** [comment]
@jonpatterns I like having a list of things I'm working on that I can edit as I go, just so I can keep track of things and so people can see what I'm generally up to. If it was in a readme in the repo, maybe I couldn't edit it so easily - I don't know, I'm new to all this. I guess it would make more sense in a Wiki, but then I don't know what kind of work would be involved in setting that up.

I like the idea of a title page, even if it's just some intro music and a cool swooshy graphic :) I'm always up for more swooshy stuff!

**Comment by jimfrize** [comment]
Okay, gunna remove the "no sound on startup" issue from the list. It only occurs with my offline version. If I upload it to a server it works perfect every time. Incidentally, I've never experienced any lag or delay time in the music starting when I play the game "live", everything seems to load pretty much instantaneously. Humm, no looping issue either - cool :)

**Comment by metalx1000** [comment]
I've added a fullscreen button next to the mute button.
I think we should create a new "issue" for each item, that way we can close them as we go along.
Label them "enhancement" if it's something we want to add, "question" if it's something to discuss,  "bug" if it's a bug, etc.

**Comment by metalx1000** [comment]
@jimfrize I've changed it so each Jetpack gives you only 50% power, and caps you at 100%.  That way you're not flying around as long with one pack, but you can collect more.

**Comment by jimfrize** [comment]
@metalx1000 Good idea. I made a pull request earlier, not sure if I have done it right, it says that there's no files to change? There should be 15 changes

**Comment by jimfrize** [comment]
Okay, will open a bunch of other individual issues in place of this one
